"""
Base strategy interface and strategy registry.

All strategies must implement BaseStrategy. Register them with StrategyRegistry
so the BotWorker can instantiate them by name.
"""

import json
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple, Type

from src.utils.logger import get_logger

logger = get_logger(__name__)


class SignalDirection(Enum):
    """Trade signal direction."""
    LONG = "long"
    SHORT = "short"
    NEUTRAL = "neutral"


@dataclass
class TradeSignal:
    """
    Trade signal generated by a strategy.

    Contains all information needed to execute a trade.
    """
    direction: SignalDirection
    confidence: int  # 0-100
    symbol: str
    entry_price: float
    target_price: float | None  # Take profit target (None = no TP)
    stop_loss: float | None  # Stop loss (None = no SL)
    reason: str
    metrics_snapshot: dict
    timestamp: datetime
    trailing_callback_pct: float | None = None  # Trail distance in % for native exchange trailing stop
    trailing_trigger_price: float | None = None  # Activation price for native trailing stop

    def to_dict(self) -> dict:
        """Convert to dictionary."""
        return {
            "direction": self.direction.value,
            "confidence": self.confidence,
            "symbol": self.symbol,
            "entry_price": self.entry_price,
            "target_price": self.target_price,
            "stop_loss": self.stop_loss,
            "reason": self.reason,
            "timestamp": self.timestamp.isoformat(),
            "trailing_callback_pct": self.trailing_callback_pct,
            "trailing_trigger_price": self.trailing_trigger_price,
        }


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    Every strategy must implement:
    - generate_signal: Analyze market and produce a TradeSignal
    - should_trade: Decide if a signal is worth executing
    - get_param_schema: Return JSON schema of configurable parameters
    """

    def __init__(self, params: Optional[Dict[str, Any]] = None):
        """
        Initialize strategy with optional parameters.

        Args:
            params: Strategy-specific parameters (from bot_config.strategy_params)
        """
        self.params = params or {}

    async def should_exit(
        self,
        symbol: str,
        side: str,
        entry_price: float,
        metrics_at_entry: dict | None = None,
        **kwargs,
    ) -> Tuple[bool, str]:
        """
        Check if an open position should be closed based on current indicators.

        Override in strategies that support indicator-based exits.
        Default: never exit (TP/SL on exchange or manual close).
        """
        return False, ""

    @abstractmethod
    async def generate_signal(self, symbol: str) -> TradeSignal:
        """
        Generate a trade signal for the given symbol.

        Args:
            symbol: Trading pair (e.g. "BTCUSDT")

        Returns:
            TradeSignal with direction, confidence, targets, reasoning
        """
        ...

    @abstractmethod
    async def should_trade(self, signal: TradeSignal) -> Tuple[bool, str]:
        """
        Decide if a signal should be executed.

        Args:
            signal: The generated trade signal

        Returns:
            Tuple of (should_trade, reason)
        """
        ...

    @classmethod
    @abstractmethod
    def get_param_schema(cls) -> Dict[str, Any]:
        """
        Return the parameter schema for this strategy.

        Used by the frontend to render a dynamic configuration form.

        Returns:
            Dict with parameter definitions. Each key is a param name, value is:
            {
                "type": "int" | "float" | "bool" | "string" | "select",
                "label": "Human readable label",
                "description": "What this parameter does",
                "default": <default_value>,
                "min": <optional_min>,
                "max": <optional_max>,
                "options": [<optional_select_options>],
            }
        """
        ...

    @classmethod
    @abstractmethod
    def get_description(cls) -> str:
        """Return a short description of the strategy."""
        ...

    async def close(self):
        """Clean up resources. Override if needed."""
        pass


def check_atr_trailing_stop(
    side: str,
    entry_price: float,
    current_price: float,
    highest_price: float,
    klines: List,
    atr_period: int = 14,
    breakeven_atr: float = 1.5,
    trail_atr: float = 2.5,
) -> Tuple[bool, str]:
    """Shared ATR-based trailing stop with breakeven floor.

    Used by EdgeIndicatorStrategy and LiquidationHunterStrategy to avoid
    duplicating the same trailing stop logic.

    Args:
        side: "long" or "short"
        entry_price: Trade entry price.
        current_price: Current market price.
        highest_price: Highest (long) or lowest (short) price since entry.
        klines: OHLCV kline data for ATR calculation.
        atr_period: ATR lookback period.
        breakeven_atr: ATR multiplier for breakeven activation threshold.
        trail_atr: ATR multiplier for trailing distance.

    Returns:
        (should_exit, reason_string)
    """
    from src.data.market_data import MarketDataFetcher

    atr_series = MarketDataFetcher.calculate_atr(klines, atr_period)
    atr_val = atr_series[-1] if atr_series else current_price * 0.015

    trail_distance = atr_val * trail_atr
    breakeven_threshold = atr_val * breakeven_atr

    if side == "long":
        was_profitable = (highest_price - entry_price) >= breakeven_threshold
        if not was_profitable:
            return False, ""

        trailing_stop = max(highest_price - trail_distance, entry_price)
        if current_price <= trailing_stop:
            pnl_pct = (current_price - entry_price) / entry_price * 100
            return True, (
                "Trailing Stop: Preis $%.2f unter Stop $%.2f "
                "(Hoechst=$%.2f, ATR=%.0f, Trail=%.1fx). PnL=%.2f%%"
                % (current_price, trailing_stop, highest_price, atr_val, trail_atr, pnl_pct)
            )
    else:
        was_profitable = (entry_price - highest_price) >= breakeven_threshold
        if not was_profitable:
            return False, ""

        trailing_stop = min(highest_price + trail_distance, entry_price)
        if current_price >= trailing_stop:
            pnl_pct = (entry_price - current_price) / entry_price * 100
            return True, (
                "Trailing Stop: Preis $%.2f über Stop $%.2f "
                "(Tiefst=$%.2f, ATR=%.0f, Trail=%.1fx). PnL=%.2f%%"
                % (current_price, trailing_stop, highest_price, atr_val, trail_atr, pnl_pct)
            )

    return False, ""


def resolve_strategy_params(
    strategy_type: Optional[str],
    strategy_params_json: Optional[str],
) -> Dict[str, Any]:
    """Resolve a strategy's effective parameter set (DEFAULTS + RISK_PROFILE + user).

    Mirrors the merge order used inside each strategy's ``__init__`` so that
    callers outside the strategy (e.g. the dashboard API, background jobs) see
    exactly the same parameters as the live strategy instance.

    Merge order:
        1. Strategy ``DEFAULTS``
        2. User-supplied ``strategy_params`` (from bot_config.strategy_params)
        3. ``RISK_PROFILES`` overrides — applied only for keys the user did
           not explicitly set.

    Args:
        strategy_type: Strategy identifier (e.g. "edge_indicator", "liquidation_hunter").
        strategy_params_json: JSON string of user params from bot_config.

    Returns:
        The fully merged parameter dict. Returns the parsed user params (or an
        empty dict) if ``strategy_type`` is unknown or the JSON is invalid —
        callers should treat a missing expected key as "strategy unsupported".
    """
    try:
        user_params = json.loads(strategy_params_json) if strategy_params_json else {}
    except (json.JSONDecodeError, TypeError):
        user_params = {}
    if not isinstance(user_params, dict):
        user_params = {}

    # Lazy imports avoid circular dependencies (strategies import from base)
    if strategy_type == "edge_indicator":
        from src.strategy.edge_indicator import DEFAULTS, RISK_PROFILES
    elif strategy_type == "liquidation_hunter":
        from src.strategy.liquidation_hunter import DEFAULTS, RISK_PROFILES
    else:
        return dict(user_params)

    merged: Dict[str, Any] = {**DEFAULTS, **user_params}
    profile = merged.get("risk_profile", "standard")
    profile_overrides = RISK_PROFILES.get(profile, {})
    for key, val in profile_overrides.items():
        if key not in user_params:  # explicit user values take precedence
            merged[key] = val
    return merged


class StrategyRegistry:
    """
    Registry of available trading strategies.

    Strategies register themselves here. The BotWorker uses this to
    instantiate the correct strategy by name.
    """
    _strategies: Dict[str, Type[BaseStrategy]] = {}
    _hidden: set = set()  # Strategies hidden from UI but still usable by existing bots

    @classmethod
    def register(cls, name: str, strategy_class: Type[BaseStrategy], hidden: bool = False):
        """Register a strategy class under a name."""
        if not issubclass(strategy_class, BaseStrategy):
            raise TypeError(f"{strategy_class} must be a subclass of BaseStrategy")
        cls._strategies[name] = strategy_class
        if hidden:
            cls._hidden.add(name)
        logger.info(f"Strategy registered: {name}{'  (hidden)' if hidden else ''}")

    @classmethod
    def get(cls, name: str) -> Type[BaseStrategy]:
        """Get a strategy class by name."""
        if name not in cls._strategies:
            available = ", ".join(cls._strategies.keys())
            raise KeyError(f"Strategy '{name}' not found. Available: {available}")
        return cls._strategies[name]

    @classmethod
    def create(cls, name: str, params: Optional[Dict[str, Any]] = None) -> BaseStrategy:
        """Create a strategy instance by name with parameters."""
        strategy_class = cls.get(name)
        return strategy_class(params=params)

    @classmethod
    def list_available(cls) -> List[Dict[str, Any]]:
        """
        List all registered strategies with their schemas.

        Returns:
            List of dicts with name, description, param_schema for each strategy.
        """
        result = []
        for name, strategy_class in cls._strategies.items():
            if name in cls._hidden:
                continue
            result.append({
                "name": name,
                "description": strategy_class.get_description(),
                "param_schema": strategy_class.get_param_schema(),
            })
        return result
