"""
Contrarian Liquidation Hunter Strategy

ROLE: Act as an "Institutional Market Maker" - maximize pain for the majority.

CORE LOGIC:
1. Analyze Leverage: Check Long/Short Account Ratio
   - IF Ratio > 2.0 (Crowded Longs): Signal is SHORT
   - IF Ratio < 0.5 (Crowded Shorts): Signal is LONG

2. Analyze Cost: Check Funding Rate
   - IF Rate > 0.05% (Expensive to Long): Strengthen SHORT confidence +20
   - IF Rate < -0.02% (Expensive to Short): Strengthen LONG confidence +20

3. Analyze Sentiment: Check Fear & Greed Index
   - IF Index > 75: Bias SHORT (Extreme Greed)
   - IF Index < 25: Bias LONG (Extreme Fear)

DECISION MATRIX:
- If Leverage AND Sentiment align (e.g., Crowded Longs + Extreme Greed):
  -> Bet AGAINST them with HIGH Confidence (85-95)
- If signals are mixed:
  -> Follow 24h trend with LOW Confidence (55-65)

CONSTRAINTS:
- NO NEUTRALITY: Must always pick a side
- Prioritize Liquidations: If Long/Short ratio is extreme, IGNORE news and price trend
- Be Decisive: No "market is uncertain" - say "High leverage signals a squeeze"
"""

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Optional, Tuple, List

from src.data.market_data import MarketMetrics, MarketDataFetcher
from src.utils.logger import get_logger
from config import settings

logger = get_logger(__name__)


class SignalDirection(Enum):
    """Trade signal direction."""
    LONG = "long"
    SHORT = "short"


@dataclass
class TradeSignal:
    """
    Trade signal generated by the strategy.

    Contains all information needed to execute a trade.
    """
    direction: SignalDirection
    confidence: int  # 0-100
    symbol: str
    entry_price: float
    target_price: float  # Take profit target
    stop_loss: float
    reason: str  # Detailed reasoning for the trade
    metrics_snapshot: dict  # Market metrics at signal generation
    timestamp: datetime

    @property
    def is_high_confidence(self) -> bool:
        """Check if this is a high confidence signal."""
        return self.confidence >= settings.strategy.high_confidence_min

    def to_dict(self) -> dict:
        """Convert to dictionary."""
        return {
            "direction": self.direction.value,
            "confidence": self.confidence,
            "symbol": self.symbol,
            "entry_price": self.entry_price,
            "target_price": self.target_price,
            "stop_loss": self.stop_loss,
            "reason": self.reason,
            "is_high_confidence": self.is_high_confidence,
            "timestamp": self.timestamp.isoformat(),
        }


class LiquidationHunterStrategy:
    """
    Contrarian Liquidation Hunter Strategy Implementation.

    This strategy acts as an institutional market maker, betting against
    the crowd when leverage and sentiment reach extreme levels.
    """

    def __init__(self, data_fetcher: Optional[MarketDataFetcher] = None):
        """
        Initialize the strategy.

        Args:
            data_fetcher: MarketDataFetcher instance (will create one if not provided)
        """
        self.data_fetcher = data_fetcher
        self.config = settings.strategy

        # Track recent signals to avoid overtrading
        self._recent_signals: List[TradeSignal] = []

    async def _ensure_fetcher(self):
        """Ensure data fetcher is available."""
        if self.data_fetcher is None:
            self.data_fetcher = MarketDataFetcher()
            await self.data_fetcher._ensure_session()

    def _analyze_leverage(self, long_short_ratio: float) -> Tuple[Optional[SignalDirection], int, str]:
        """
        Analyze leverage position based on Long/Short Ratio.

        Args:
            long_short_ratio: Current L/S ratio

        Returns:
            Tuple of (signal direction, confidence adjustment, reasoning)
        """
        crowded_longs = self.config.long_short_crowded_longs
        crowded_shorts = self.config.long_short_crowded_shorts

        if long_short_ratio > crowded_longs:
            # Crowded longs - bet on SHORT (long squeeze)
            excess = (long_short_ratio - crowded_longs) / crowded_longs * 100
            confidence_boost = min(int(excess * 2), 30)  # Up to 30 extra confidence
            reason = f"Crowded Longs detected (L/S Ratio: {long_short_ratio:.2f} > {crowded_longs}). Long squeeze imminent."
            logger.info(f"LEVERAGE SIGNAL: SHORT (L/S={long_short_ratio:.2f}, boost={confidence_boost})")
            return SignalDirection.SHORT, confidence_boost, reason

        elif long_short_ratio < crowded_shorts:
            # Crowded shorts - bet on LONG (short squeeze)
            excess = (crowded_shorts - long_short_ratio) / crowded_shorts * 100
            confidence_boost = min(int(excess * 2), 30)
            reason = f"Crowded Shorts detected (L/S Ratio: {long_short_ratio:.2f} < {crowded_shorts}). Short squeeze incoming."
            logger.info(f"LEVERAGE SIGNAL: LONG (L/S={long_short_ratio:.2f}, boost={confidence_boost})")
            return SignalDirection.LONG, confidence_boost, reason

        # Neutral leverage - no strong signal
        return None, 0, f"L/S Ratio neutral ({long_short_ratio:.2f})"

    def _analyze_funding_rate(
        self, funding_rate: float, base_direction: Optional[SignalDirection]
    ) -> Tuple[int, str]:
        """
        Analyze funding rate cost and adjust confidence.

        Args:
            funding_rate: Current funding rate (decimal)
            base_direction: Current signal direction

        Returns:
            Tuple of (confidence adjustment, reasoning)
        """
        high_threshold = self.config.funding_rate_high
        low_threshold = self.config.funding_rate_low

        funding_pct = funding_rate * 100  # Convert to percentage for display

        if funding_rate > high_threshold:
            # Expensive to long - strengthens SHORT signal
            adjustment = 20 if base_direction == SignalDirection.SHORT else -10
            reason = f"High Funding Rate ({funding_pct:.4f}%) - expensive to hold longs."
            logger.info(f"FUNDING SIGNAL: Supports SHORT (rate={funding_pct:.4f}%)")
            return adjustment, reason

        elif funding_rate < low_threshold:
            # Expensive to short - strengthens LONG signal
            adjustment = 20 if base_direction == SignalDirection.LONG else -10
            reason = f"Negative Funding Rate ({funding_pct:.4f}%) - expensive to hold shorts."
            logger.info(f"FUNDING SIGNAL: Supports LONG (rate={funding_pct:.4f}%)")
            return adjustment, reason

        return 0, f"Funding Rate neutral ({funding_pct:.4f}%)"

    def _analyze_sentiment(self, fear_greed: int) -> Tuple[Optional[SignalDirection], int, str]:
        """
        Analyze Fear & Greed sentiment.

        Args:
            fear_greed: Fear & Greed Index (0-100)

        Returns:
            Tuple of (suggested direction, confidence adjustment, reasoning)
        """
        extreme_fear = self.config.fear_greed_extreme_fear
        extreme_greed = self.config.fear_greed_extreme_greed

        if fear_greed > extreme_greed:
            # Extreme Greed - market top signal, go SHORT
            excess = fear_greed - extreme_greed
            confidence_boost = min(excess, 20)
            reason = f"Extreme Greed ({fear_greed}) - market euphoria, reversal expected."
            logger.info(f"SENTIMENT SIGNAL: SHORT (FGI={fear_greed})")
            return SignalDirection.SHORT, confidence_boost, reason

        elif fear_greed < extreme_fear:
            # Extreme Fear - market bottom signal, go LONG
            excess = extreme_fear - fear_greed
            confidence_boost = min(excess, 20)
            reason = f"Extreme Fear ({fear_greed}) - capitulation phase, bounce expected."
            logger.info(f"SENTIMENT SIGNAL: LONG (FGI={fear_greed})")
            return SignalDirection.LONG, confidence_boost, reason

        return None, 0, f"Sentiment neutral (FGI={fear_greed})"

    def _get_trend_direction(self, price_change_24h: float) -> SignalDirection:
        """
        Get trend direction based on 24h price change.

        Args:
            price_change_24h: 24-hour price change percentage

        Returns:
            Signal direction following the trend
        """
        if price_change_24h > 0:
            return SignalDirection.LONG
        return SignalDirection.SHORT

    def _calculate_targets(
        self,
        direction: SignalDirection,
        current_price: float,
        volatility: float = 3.5,
    ) -> Tuple[float, float]:
        """
        Calculate take profit and stop loss targets.

        Args:
            direction: Trade direction
            current_price: Current asset price
            volatility: Expected volatility percentage (default 3.5%)

        Returns:
            Tuple of (take_profit_price, stop_loss_price)
        """
        # Target: 3-4% in predicted direction based on daily volatility
        take_profit_pct = settings.trading.take_profit_percent / 100
        stop_loss_pct = settings.trading.stop_loss_percent / 100

        if direction == SignalDirection.LONG:
            take_profit = current_price * (1 + take_profit_pct)
            stop_loss = current_price * (1 - stop_loss_pct)
        else:  # SHORT
            take_profit = current_price * (1 - take_profit_pct)
            stop_loss = current_price * (1 + stop_loss_pct)

        return round(take_profit, 2), round(stop_loss, 2)

    async def generate_signal(self, symbol: str = "BTCUSDT") -> TradeSignal:
        """
        Generate a trade signal based on current market conditions.

        This is the main strategy logic that analyzes all metrics and
        produces a definitive trade signal (NO NEUTRALITY ALLOWED).

        Args:
            symbol: Trading pair to analyze

        Returns:
            TradeSignal with direction, confidence, and reasoning
        """
        await self._ensure_fetcher()

        logger.info(f"=== Generating Signal for {symbol} ===")

        # Fetch all market metrics
        metrics = await self.data_fetcher.fetch_all_metrics()

        # Get the appropriate funding rate and price
        if "BTC" in symbol:
            funding_rate = metrics.funding_rate_btc
            current_price = metrics.btc_price
            price_change = metrics.btc_24h_change_percent
        else:
            funding_rate = metrics.funding_rate_eth
            current_price = metrics.eth_price
            price_change = metrics.eth_24h_change_percent

        # Initialize analysis
        reasons = []
        confidence = 50  # Start neutral

        # === STEP 1: Analyze Leverage ===
        leverage_direction, leverage_conf, leverage_reason = self._analyze_leverage(
            metrics.long_short_ratio
        )
        reasons.append(leverage_reason)
        confidence += leverage_conf

        # === STEP 2: Analyze Sentiment ===
        sentiment_direction, sentiment_conf, sentiment_reason = self._analyze_sentiment(
            metrics.fear_greed_index
        )
        reasons.append(sentiment_reason)
        confidence += sentiment_conf

        # === STEP 3: Determine Direction ===
        final_direction = None

        # PRIORITY 1: If Leverage AND Sentiment align -> HIGH CONFIDENCE contrarian bet
        if leverage_direction and sentiment_direction:
            if leverage_direction == sentiment_direction:
                # Strong alignment - HIGH CONFIDENCE
                final_direction = leverage_direction
                confidence = max(confidence, self.config.high_confidence_min)
                reasons.append(
                    f"ALIGNMENT: Leverage ({leverage_direction.value.upper()}) + "
                    f"Sentiment ({sentiment_direction.value.upper()}) = "
                    f"HIGH CONFIDENCE {leverage_direction.value.upper()}"
                )
                logger.info(f"STRONG ALIGNMENT: {leverage_direction.value.upper()} with {confidence}% confidence")
            else:
                # Conflicting signals - follow leverage (it's more actionable)
                final_direction = leverage_direction
                confidence = min(confidence, 70)  # Cap at 70%
                reasons.append(
                    f"CONFLICT: Leverage says {leverage_direction.value.upper()}, "
                    f"Sentiment says {sentiment_direction.value.upper()}. "
                    f"Following Leverage signal."
                )

        # PRIORITY 2: If only leverage signal is extreme -> Trust it
        elif leverage_direction:
            final_direction = leverage_direction
            reasons.append(f"Leverage-driven signal: {leverage_direction.value.upper()}")

        # PRIORITY 3: If only sentiment is extreme -> Trust it
        elif sentiment_direction:
            final_direction = sentiment_direction
            reasons.append(f"Sentiment-driven signal: {sentiment_direction.value.upper()}")

        # PRIORITY 4: No extreme signals -> Follow the trend (LOW CONFIDENCE)
        else:
            final_direction = self._get_trend_direction(price_change)
            confidence = max(self.config.low_confidence_min, min(confidence, 65))
            reasons.append(
                f"No extreme signals. Following 24h trend "
                f"({price_change:+.2f}%): {final_direction.value.upper()}"
            )
            logger.info(f"TREND FOLLOWING: {final_direction.value.upper()} with {confidence}% confidence")

        # === STEP 4: Analyze Funding Rate (Adjust Confidence) ===
        funding_adj, funding_reason = self._analyze_funding_rate(funding_rate, final_direction)
        confidence += funding_adj
        reasons.append(funding_reason)

        # === STEP 5: Clamp Confidence ===
        confidence = max(self.config.low_confidence_min, min(confidence, 95))

        # === STEP 6: Validate Price and Calculate Targets ===
        if current_price <= 0:
            logger.error(f"Invalid price for {symbol}: {current_price}. Using fallback.")
            # Signal will be rejected by should_trade() due to invalid price
            take_profit, stop_loss = 0.0, 0.0
        else:
            take_profit, stop_loss = self._calculate_targets(final_direction, current_price)

        # Build reasoning summary
        full_reason = " | ".join(reasons)

        # Create the signal
        signal = TradeSignal(
            direction=final_direction,
            confidence=confidence,
            symbol=symbol,
            entry_price=current_price,
            target_price=take_profit,
            stop_loss=stop_loss,
            reason=full_reason,
            metrics_snapshot=metrics.to_dict(),
            timestamp=datetime.now(),
        )

        logger.info(f"=== SIGNAL GENERATED ===")
        logger.info(f"Direction: {signal.direction.value.upper()}")
        logger.info(f"Confidence: {signal.confidence}%")
        logger.info(f"Entry: ${signal.entry_price:,.2f}")
        logger.info(f"Target: ${signal.target_price:,.2f}")
        logger.info(f"Stop Loss: ${signal.stop_loss:,.2f}")
        logger.info(f"Reason: {signal.reason}")

        self._recent_signals.append(signal)
        return signal

    async def should_trade(self, signal: TradeSignal) -> Tuple[bool, str]:
        """
        Determine if a signal should be executed based on confidence and conditions.

        Args:
            signal: TradeSignal to evaluate

        Returns:
            Tuple of (should_trade: bool, reason: str)
        """
        # Minimum confidence threshold
        min_confidence = self.config.low_confidence_min

        if signal.confidence < min_confidence:
            return False, f"Confidence ({signal.confidence}%) below minimum ({min_confidence}%)"

        # Check if price is valid
        if signal.entry_price <= 0:
            return False, "Invalid entry price"

        # Additional checks can be added here (time-based, drawdown, etc.)

        return True, f"Signal approved with {signal.confidence}% confidence"

    def get_position_size_recommendation(
        self,
        signal: TradeSignal,
        account_balance: float,
    ) -> float:
        """
        Calculate recommended position size based on signal confidence.

        High confidence signals get larger positions, low confidence get smaller.

        Args:
            signal: Trade signal
            account_balance: Available balance

        Returns:
            Recommended position size in USDT
        """
        base_size_pct = settings.trading.position_size_percent

        # Scale position size with confidence
        if signal.confidence >= 90:
            multiplier = 1.5
        elif signal.confidence >= 80:
            multiplier = 1.25
        elif signal.confidence >= 70:
            multiplier = 1.0
        elif signal.confidence >= 60:
            multiplier = 0.75
        else:
            multiplier = 0.5

        position_pct = base_size_pct * multiplier
        position_size = account_balance * (position_pct / 100)

        logger.info(
            f"Position Size: {position_pct:.1f}% of ${account_balance:,.2f} = ${position_size:,.2f} "
            f"(confidence multiplier: {multiplier}x)"
        )

        return position_size

    async def close(self):
        """Clean up resources."""
        if self.data_fetcher:
            await self.data_fetcher.close()
