"""Central Prometheus metric definitions (#327 PR-1).

Scope
-----
This module owns the ``REGISTRY`` that the flag-gated ``/metrics``
endpoint scrapes, plus the definition of every metric the observability
rollout will emit. **No ``.inc()`` / ``.observe()`` / ``.set()`` call
sites live here** — they are added to the HTTP middleware, BotWorker
components, RiskStateManager, and ExchangeClient adapters in PR-2..4
of issue #327.

A dedicated ``CollectorRegistry`` is used instead of the
``prometheus_client`` default registry so:

* test isolation — tests can instantiate a fresh module-level registry
  without colliding with the existing ``src/monitoring/metrics.py``
  definitions that still use the default registry (those will be
  migrated/retired in a follow-up).
* explicit scoping — the /metrics endpoint renders exactly the metrics
  owned by the observability package, never process-global GC/GIL
  counters that Prometheus auto-registers at import time.

Label cardinality
-----------------
Labels are chosen to stay below the Prometheus "keep under 10k active
series per metric" guidance:

* ``path`` labels are template-collapsed by the HTTP middleware
  (``/api/bots/{id}``, not ``/api/bots/42``) — PR-2 owns that
  normalization.
* ``bot_id`` is OK because the number of active bots per VPS is small
  (< 100 in the current deployment).
* No user-identifying labels (email, wallet address, API key) ever
  appear here — bot_id + exchange is sufficient to drill down in
  Grafana without leaking PII.
"""

from __future__ import annotations

from prometheus_client import (
    CONTENT_TYPE_LATEST,
    CollectorRegistry,
    Counter,
    Gauge,
    Histogram,
    generate_latest,
)


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

REGISTRY: CollectorRegistry = CollectorRegistry()
"""The single registry scraped by the flag-gated ``/metrics`` endpoint."""


# ---------------------------------------------------------------------------
# HTTP (instrumented by src/api/middleware/metrics.py in PR-2)
# ---------------------------------------------------------------------------

HTTP_REQUESTS_TOTAL = Counter(
    "http_requests_total",
    "Total HTTP requests observed by the FastAPI application.",
    ["method", "path", "status"],
    registry=REGISTRY,
)

HTTP_REQUEST_DURATION_SECONDS = Histogram(
    "http_request_duration_seconds",
    "HTTP request duration in seconds (wall clock).",
    ["method", "path"],
    buckets=(0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
    registry=REGISTRY,
)

HTTP_REQUESTS_IN_FLIGHT = Gauge(
    "http_requests_in_flight",
    "In-flight HTTP requests currently being handled.",
    ["method", "path"],
    registry=REGISTRY,
)


# ---------------------------------------------------------------------------
# Bot (instrumented by BotWorker / TradeExecutor / PositionMonitor in PR-3)
# ---------------------------------------------------------------------------

BOT_SIGNALS_GENERATED_TOTAL = Counter(
    "bot_signals_generated_total",
    "Total trading signals generated by a bot's strategy.",
    ["bot_id", "exchange", "strategy", "side"],
    registry=REGISTRY,
)

BOT_TRADES_EXECUTED_TOTAL = Counter(
    "bot_trades_executed_total",
    "Total trade-execution attempts grouped by outcome "
    "(result in {success, rejected, failed}).",
    ["bot_id", "exchange", "mode", "result"],
    registry=REGISTRY,
)

BOT_TRADE_EXECUTION_DURATION_SECONDS = Histogram(
    "bot_trade_execution_duration_seconds",
    "Wall-clock duration of the TradeExecutor's submit-to-ack path.",
    ["exchange"],
    buckets=(0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0),
    registry=REGISTRY,
)

BOT_POSITION_MONITOR_TICK_DURATION_SECONDS = Histogram(
    "bot_position_monitor_tick_duration_seconds",
    "Wall-clock duration of one PositionMonitor tick per bot.",
    ["bot_id"],
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0),
    registry=REGISTRY,
)

BOT_OPEN_POSITIONS = Gauge(
    "bot_open_positions",
    "Number of currently open positions per bot and exchange.",
    ["bot_id", "exchange"],
    registry=REGISTRY,
)

BOT_DAILY_PNL = Gauge(
    "bot_daily_pnl",
    "Realized PnL for the current UTC day per bot and exchange "
    "(quote currency, typically USDT).",
    ["bot_id", "exchange"],
    registry=REGISTRY,
)


# ---------------------------------------------------------------------------
# Risk (instrumented by RiskStateManager / TradeGate in PR-4)
# ---------------------------------------------------------------------------

RISK_TRADE_GATE_DECISIONS_TOTAL = Counter(
    "risk_trade_gate_decisions_total",
    "Decisions emitted by the risk trade-gate "
    "(decision in {allow, block_max_trades, block_daily_loss}).",
    ["bot_id", "decision"],
    registry=REGISTRY,
)

RISK_ALERTS_EMITTED_TOTAL = Counter(
    "risk_alerts_emitted_total",
    "Risk-manager alerts that were emitted to downstream notifiers.",
    ["bot_id", "alert_type"],
    registry=REGISTRY,
)


# ---------------------------------------------------------------------------
# Exchange (instrumented by ExchangeClient adapters in PR-4)
# ---------------------------------------------------------------------------

EXCHANGE_API_REQUESTS_TOTAL = Counter(
    "exchange_api_requests_total",
    "Total REST requests sent to an exchange adapter, grouped by "
    "endpoint and status.",
    ["exchange", "endpoint", "status"],
    registry=REGISTRY,
)

EXCHANGE_API_REQUEST_DURATION_SECONDS = Histogram(
    "exchange_api_request_duration_seconds",
    "Wall-clock duration of an exchange REST request.",
    ["exchange", "endpoint"],
    buckets=(0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
    registry=REGISTRY,
)

EXCHANGE_WEBSOCKET_CONNECTED = Gauge(
    "exchange_websocket_connected",
    "Whether the exchange WebSocket listener is currently connected "
    "(1 = connected, 0 = disconnected).",
    ["exchange"],
    registry=REGISTRY,
)


# ---------------------------------------------------------------------------
# System
# ---------------------------------------------------------------------------

APP_BUILD_COMMIT = Gauge(
    "app_build_commit",
    "Build identification as a label-only gauge (value always 1). "
    "The commit label carries the deployed git SHA, read from the "
    "BUILD_COMMIT env var at process start if present.",
    ["commit"],
    registry=REGISTRY,
)

APP_FEATURE_FLAGS = Gauge(
    "app_feature_flags",
    "Current value of every registered feature flag "
    "(enabled label is the string 'true'/'false').",
    ["flag", "enabled"],
    registry=REGISTRY,
)


# ---------------------------------------------------------------------------
# Rendering helper
# ---------------------------------------------------------------------------

def render_latest() -> bytes:
    """Render the REGISTRY in Prometheus text exposition format."""
    return generate_latest(REGISTRY)
